/*
 * SPDX-FileCopyrightText: 2022-2026 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @file
 * @brief This file was generated by esp_mmap_assets, don't modify it
 */

#pragma once

#include "esp_mmap_assets.h"

#define MMAP_ASSETS_FILES           1
#define MMAP_ASSETS_CHECKSUM        0x5A0E

enum MMAP_ASSETS_LISTS {
    MMAP_ASSETS_FONT_PUHUI_COMMON_16_4_BIN = 0,        /*!< font_puhui_common_16_4.bin */
};
